### ISSUE TITLE
Jupyter book latex - inner margin / gutter

### ISSUE THREAD

**Issue by psychemedia** [psychemedia/amazon_publishing_notes#1]
In `_config.yml` something like:

```yaml
sphinx:
  config:
    #html_copy_source: false
    latex_elements:
      preamble: |
        % First, reset geometry options
        \AtBeginDocument{
          \clearpage
          \newgeometry{twoside,inner=1.5in,outer=1in,top=1in,bottom=1in}
        }

  extra_extensions:

latex:
  latex_documents:
    targetname: testbookX.tex
  use_jupyterbook_latex: true
  latex_engine: xelatex
```

jb build --toc _toc_custom.yml --config _config_custom.yml --builder pdflatex .
